### ISSUE TITLE
Delayed resync raises NotImplementedError

### ISSUE THREAD

**Issue by carbn** [truveris/py-mdstat#1]
Here's a sample mdstat output triggering the error:

```
Personalities : [raid0] [raid1] [raid6] [raid5] [raid4] 
md1 : active raid1 sdb2[1] sda2[0]
      16760832 blocks super 1.2 [2/1] [U_]
        resync=DELAYED

md0 : active raid1 sdb1[1] sda1[0]
      4190208 blocks super 1.2 [2/1] [U_]
      [==========>..........]  recovery = 54.0% (2264768/4190208) finish=0.4min speed=68084K/sec

unused devices: <none>
```

This situation occurs when a single disk has two md raids and both are being resynced at the same time. The second one is delayed until the first finishes. I fixed it locally with the following patch:

```
diff --git a/mdstat/device.py b/mdstat/device.py
index 1a4dfbb..d894b5d 100644
--- a/mdstat/device.py
+++ b/mdstat/device.py
@@ -28,6 +28,8 @@ def parse_device(lines):
             bitmap = parse_device_bitmap(line)
         elif line.startswith("      ["):
             resync = parse_device_resync(line)
+        elif line.startswith("        resync=DELAYED"):
+            resync = None
         else:
             raise NotImplementedError("unknown device line: {}".format(line))
```

**Comment by tamentis** [comment]
If I read https://github.com/torvalds/linux/blob/master/drivers/md/md.c properly the resync=DELAYED should be prefixed with a tab (\t) character, can you confirm that?  Could you email me your mdstat file as-is by any chance?

**Comment by tamentis** [comment]
Can you pull and test my last commit? I removed the `sync_request` property on the device and put the "resync=PENDING" and "resync=DELAYED" on the "operation" property of "resync".

**Comment by carbn** [comment]
The new version seems to be working correctly. Thanks again for your quick fix :)
